test:
  workers:
    type: local
    number: 1
  rounds:
  # -----Channel1-----------------#
    - label: Channel1 - Round 1 - Create Patient Data - Contract 1
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract1.js
    - label: Channel1 - Round 2 - Create Patient Data - Contract 1
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract1.js
    - label: Channel1 - Round 3 - Create Patient Data - Contract 1
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 70
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract1.js
    - label: Channel1 - Round 5 - Get Patient Data  - Contract 1
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 150
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract1.js
    - label: Channel1 - Round 6 - Get Patient Data - Contract 1
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 160
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract1.js
    - label: Channel1 - Round 7 - Get Patient Data  - Contract 1
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract1.js

# -----Channel2-----------------#

    # - label: Channel2 - Round 1 - Create Patient Data - Contract 2
    #   txNumber: 100
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 30
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract2.js
    # - label: Channel2 - Round 2 - Create Patient Data - Contract 2
    #   txNumber: 200
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 60
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract2.js
    # - label: Channel2 - Round 3 - Create Patient Data - Contract 2
    #   txNumber: 200
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 20
    #   workload:
    #       module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract2.js
    # - label: Channel2 - Round 5 - Get Patient Data  - Contract 2
    #   txNumber: 2000
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #       module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract2.js
    # - label: Channel2 - Round 6 - Get Patient Data - Contract 2
    #   txNumber: 2000
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 200
    #   workload:
    #       module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract2.js
        
# # ----------Channel3-----------------#
#     - label: Channel3 - Round 1 - Create Patient Data - Contract 3
#       txNumber: 100
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 30
#       workload:
#         module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract3.js
#     - label: Channel3 - Round 2 - Create Patient Data - Contract 3
#       txNumber: 200
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 60
#       workload:
#         module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract3.js
#     - label: Channel3 - Round 3 - Create Patient Data - Contract 3
#       txNumber: 200
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 20
#       workload:
#           module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract3.js
#     - label: Channel3 - Round 5 - Get Patient Data  - Contract 3
#       txNumber: 2000
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 150
#       workload:
#           module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract3.js
#     - label: Channel3 - Round 6 - Get Patient Data - Contract 3
#       txNumber: 2000
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 160
#       workload:
#           module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract3.js

# # ------------Channel4-----------------#

#     - label: Channel4 - Round 1 - Create Patient Data - Contract 4
#       txNumber: 100
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 30
#       workload:
#         module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract4.js
#     - label: Channel4 - Round 2 - Create Patient Data - Contract 4
#       txNumber: 200
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 60
#       workload:
#         module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract4.js
#     - label: Channel4 - Round 5 - Get Patient Data  - Contract 4
#       txNumber: 2000
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 150
#       workload:
#           module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract4.js
#     - label: Channel4 - Round 6 - Get Patient Data - Contract 4
#       txNumber: 2000
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 200
#       workload:
#           module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract4.js
#     - label: Channel4 - Round 7 - Get Patient Data  - Contract 4
#       txNumber: 1500
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 160
#       workload:
#           module: benchmarks/scenario/simple/pavan-v2.2/queryPatientContract4.js
