test:
  workers:
    type: local
    number: 1
  rounds:
    - label: Round 1 - Create Patient Data - Contract 1
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/createPatient.js
    - label: Round 1.1 - Create Patient Data - Contract 1
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 60
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/createPatient.js
    - label: Round 2 - Create Patient Data - Contract 1
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 20
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/createPatient.js
    - label: Round 3 - Create Patient Data - Contract 1
      txNumber: 400
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/createPatient.js
    - label: Round 4 - Get Patient Data  - Contract 1
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 150
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/queryPatient.js
    - label: Round 4 - Get Patient Data - Contract 1
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/queryPatient.js
    - label: Round 5 - Get Patient Data  - Contract 1
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/queryPatient.js
    - label: Round 5.1 - Get Patient Data - Contract 1
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 250
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/queryPatient.js

    - label: Round 1 - Create Patient Data - Contract 2
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/createPatientContract2.js

    # - label: Create Car 2
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 3
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 4
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 5
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 6
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js