test:
  workers:
    type: local
    number: 1
  rounds:
    - label: Create Sensor Data 1
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 120
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/createIOTData.js
    - label: Create Sensor Data 2
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 120
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/createIOTData.js

    # - label: Create Car 2
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 3
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 4
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 5
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 6
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js